"""ajuste de models, nomes tabela

Revision ID: 107af0db29cf
Revises: c67cdd98ad8c
Create Date: 2025-09-21 11:57:33.963609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '107af0db29cf'
down_revision = 'c67cdd98ad8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Producao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_producao', sa.String(length=50), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('densidade', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('ComponenteProducao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producao_id', sa.Integer(), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('quantidade_usada', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['producao_id'], ['Producao.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['Produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('producoes')
    op.drop_table('componentes_producao')
    op.drop_table('produtos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('componentes_producao',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('producao_id', sa.INTEGER(), nullable=True),
    sa.Column('produto_id', sa.INTEGER(), nullable=True),
    sa.Column('quantidade_usada', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['producao_id'], ['producoes.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producoes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_producao', sa.VARCHAR(length=50), nullable=False),
    sa.Column('data', sa.DATE(), nullable=False),
    sa.Column('densidade', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ComponenteProducao')
    op.drop_table('Produto')
    op.drop_table('Producao')
    # ### end Alembic commands ###
