"""AJUSTADO MODELS PARA CONTROLE DE ESTOQUE

Revision ID: 3f61c2d6cf72
Revises: 107af0db29cf
Create Date: 2025-09-21 16:29:05.569653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f61c2d6cf72'
down_revision = '107af0db29cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Movimentacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('producao_id', sa.Integer(), nullable=True))
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=False)
        # Corrigido: adicionado nome para constraint
        batch_op.create_foreign_key(
            'fk_movimentacao_producao_id',  # <- nome da constraint
            'Producao',
            ['producao_id'],
            ['id']
        )
        batch_op.drop_column('saldo_apos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Movimentacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saldo_apos', sa.FLOAT(), nullable=False))
        # Corrigido: nome da constraint precisa ser informado
        batch_op.drop_constraint('fk_movimentacao_producao_id', type_='foreignkey')
        batch_op.alter_column('tipo',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('producao_id')

    # ### end Alembic commands ###
