"""Adiciona coluna cor em users

Revision ID: 630e116631ff
Revises: 
Create Date: 2025-09-14 20:45:16.142071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '630e116631ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cor', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('cor')

    # ### end Alembic commands ###
