"""Criando tabelas Users e Endereco

Revision ID: c02534659d2a
Revises: bb331fa2b815
Create Date: 2025-09-16 12:42:26.018422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c02534659d2a'
down_revision = 'bb331fa2b815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endereco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('rua', sa.String(length=100), nullable=False),
    sa.Column('bairro', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('enderecos')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('cidade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cidade', sa.VARCHAR(length=100), nullable=True))

    op.create_table('enderecos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rua', sa.VARCHAR(length=100), nullable=False),
    sa.Column('cidade', sa.VARCHAR(length=50), nullable=False),
    sa.Column('estado', sa.VARCHAR(length=50), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('endereco')
    # ### end Alembic commands ###
