"""ajuste de models

Revision ID: c67cdd98ad8c
Revises: 
Create Date: 2025-09-21 11:28:11.013780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c67cdd98ad8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_producao', sa.String(length=50), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('densidade', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('componentes_producao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producao_id', sa.Integer(), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('quantidade_usada', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['producao_id'], ['producoes.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('producao')
    op.drop_table('componente_producao')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('componente_producao',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('comp_a', sa.FLOAT(), nullable=True),
    sa.Column('comp_b', sa.FLOAT(), nullable=True),
    sa.Column('comp_c', sa.FLOAT(), nullable=True),
    sa.Column('producao_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['producao_id'], ['producao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producao',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_producao', sa.VARCHAR(length=50), nullable=False),
    sa.Column('data', sa.DATE(), nullable=False),
    sa.Column('densidade', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('componentes_producao')
    op.drop_table('produtos')
    op.drop_table('producoes')
    # ### end Alembic commands ###
